---
apiVersion: v1
kind: Service
metadata:
  name: notification-worker
  namespace: notifications
  labels:
    app: notification-worker
spec:
  selector:
    app: notification-worker
  ports:
    - name: client
      port: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
  namespace: notifications
  labels:
    app: notification-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64    
      containers:
        - name: notification-worker
          image: "{{IMAGE}}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: notifications-configs
            - secretRef:
                name: notifications-secrets

          env:
            - name: JETSTREAM_NATS_CLIENTNAME
              value: "notification-worker"