---
apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: notifications
  labels:
    app: notifications
spec:
  selector:
    app: notifications
  ports:
    - name: client
      port: 80
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-configs
  namespace: notifications
data:
  NOTIFICATIONS_SERVER_PORT: ":80"
  NOTIFICATIONS_STAGE: "dev"
  ################
  JETSTREAM_NATS_URL: "nats://nats1.dev.my.cloud:4222"
  JETSTREAM_NATS_CLIENTNAME: "notifications"
  ################
  SENTRY_SERVERNAME: "notifications-service"
  SENTRY_ENVIRONMENT: "Dev"
  ################
  LOGGER_LEVEL: "debug"
  LOGGER_ENV: "dev"
  ################
  REDIS_URL: "redis-1.dev.my.cloud"
  REDIS_PASSWORD: ""
  REDIS_CLUSTER: "false"
  ################
  FILEMANAGER_STORAGEURL: "https://static.my.cloud/"
  ################
  EMAIL_HOST: "smtp.eu.my.org"
  EMAIL_PORT: "587"
  EMAIL_FROM: "noreply@my.tj"
  ################
  SMS_URL: "https://sms.my.net"
  ################
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  namespace: notifications
  labels:
    app: notifications
spec:
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64    
      volumes:
        - name: config-volume
          configMap:
            name: firebase-config

      containers:
        - name: notifications
          image: "{{IMAGE}}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          volumeMounts:
            - name: config-volume
              mountPath: /app/firebase.json
              subPath: firebase.json

          envFrom:
            - configMapRef:
                name: notifications-configs
            - secretRef:
                name: notifications-secrets

          env:
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory

            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          livenessProbe:
            httpGet:
              path: /api/notifications-internal/v1/health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /api/notifications-internal/v1/health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
