name: code checker

on:
  workflow_dispatch:
  pull_request_review:
    types: [ submitted ]

jobs:
  check:
    runs-on: ubuntu-24.04
    environment: development
    
    strategy:
      matrix:
        component: [ notifications ]
    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: go version

      - name: Run Go linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.0
          only-new-issues: true

      - name: Run structs alignment
        uses: essentialkaos/aligo-action@v2
        with:
          files: ./...

      - name: Verify dependencies
        run: go mod verify

      - name: Run test for ${{ matrix.component }}
        run: go test -v -run Test_Deps cmd/${{ matrix.component }}/main_test.go
